version: "3.8"

services:
  db:
    image: postgres:13.2-alpine
    container_name: "users-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=branton98
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data
  
  api:
    build: .
    container_name: "users-rest-api"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "branton98"
      DB_HOST: "host.docker.internal"
      DB_TABLE: "postgres"
      DB_DB: "postgres"
      DB_PORT: "5432"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres: 

networks:
  fullstack:
    driver: bridge